/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author IZZA
 */
public class suborgan extends javax.swing.JFrame {

    /**
     * Creates new form suborgan
     */
    public suborgan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        harilat = new javax.swing.JTextField();
        harifrm = new javax.swing.JTextField();
        anggota = new javax.swing.JTextField();
        pres = new javax.swing.JTextField();
        namakt = new javax.swing.JTextField();
        sub = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Daftar Sub Organ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(108, 19, 190, 29);

        jLabel7.setText("Prestasi");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 290, 110, 14);

        jLabel8.setText("Jumlah Anggota");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 250, 90, 14);

        jLabel9.setText("Hari Forum");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 210, 90, 14);

        jLabel10.setText("Hari Latihan");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 170, 90, 14);

        jLabel11.setText("Nama Ketua");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 130, 90, 14);

        jLabel13.setText("Sub Organisasi");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(30, 70, 110, 14);
        getContentPane().add(harilat);
        harilat.setBounds(150, 170, 190, 30);
        getContentPane().add(harifrm);
        harifrm.setBounds(150, 210, 190, 30);
        getContentPane().add(anggota);
        anggota.setBounds(150, 250, 190, 30);
        getContentPane().add(pres);
        pres.setBounds(150, 290, 190, 30);
        getContentPane().add(namakt);
        namakt.setBounds(150, 130, 190, 30);

        sub.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Nama Sub Organ-", "Paskibra", "PMR", "Palwaga" }));
        sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subActionPerformed(evt);
            }
        });
        getContentPane().add(sub);
        sub.setBounds(150, 70, 190, 20);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setForeground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subActionPerformed
        // TODO add your handling code here:
        if (sub.getSelectedItem().equals("Paskibra")){
            namakt.setText("Abel Bima Wiratama");
            harilat.setText("Sabtu");
            harifrm.setText("Selasa");
            anggota.setText("38");
            pres.setText("LKBB Jatim");
          
        }
        else
        if(sub.getSelectedItem().equals("PMR")){
            namakt.setText("M. Nur Arifin");
            harilat.setText("Jumat");
            harifrm.setText("Senin");
            anggota.setText("43");
            pres.setText("Juara PPGD Kota Malang");
        }
        else
        if(sub.getSelectedItem().equals("Palwaga")){
            namakt.setText("Prasetya Ananta W. S.");
            harilat.setText("Kamis");
            harifrm.setText("Tidak ada");
            anggota.setText("45");
            pres.setText("Mendaki gunung di Jawa Timur");
            
        }

    }//GEN-LAST:event_subActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(suborgan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(suborgan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(suborgan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(suborgan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new suborgan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anggota;
    private javax.swing.JTextField harifrm;
    private javax.swing.JTextField harilat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField namakt;
    private javax.swing.JTextField pres;
    private javax.swing.JComboBox<String> sub;
    // End of variables declaration//GEN-END:variables
}
